### ISSUE TITLE
我在vue项目中运行以后屏幕一片白

### ISSUE THREAD

**Issue by gouxiwen** [chrisbing/electorn-capture-screen#3]
控制台报了这样的错误：
Not allowed to load local resource: file:///Users/ex-gouxiwen001/Desktop/electron-webIM/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/src/lib/capture.html
我的vue项目是用simulatedgreg/electron-vue脚手架搭建的

**Comment by CQBoyBrand** [comment]
> 控制台报了这样的错误：
> Not allowed to load local resource: file:///Users/ex-gouxiwen001/Desktop/electron-webIM/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/src/lib/capture.html
> 我的vue项目是用simulatedgreg/electron-vue脚手架搭建的

你好，这个问题你是怎么解决的
